// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read from environment variables with fallback to prevent silent failures
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://yerzsrkrjsfimihuffgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllcnpzcmtyanNmaW1paHVmZmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxMjM5NDcsImV4cCI6MjA4MzY5OTk0N30.9RWJjhm1560rMzSxwWh5dRzKaArmefSvXATvtebt1-c";

// Validate configuration at module load time
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [];
  if (!import.meta.env.VITE_SUPABASE_URL) missing.push('VITE_SUPABASE_URL');
  if (!import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY) missing.push('VITE_SUPABASE_PUBLISHABLE_KEY');
  console.error(
    'Supabase configuration missing. Environment variables not set: ' + missing.join(', ') + 
    '. The app may not function correctly. Check your .env file.'
  );
}

// Create auth config with safe localStorage access
let authConfig: any = {
  persistSession: true,
  autoRefreshToken: true,
};

// Safely use localStorage if available
try {
  if (typeof window !== 'undefined' && window.localStorage) {
    authConfig.storage = window.localStorage;
  }
} catch (e) {
  console.warn('localStorage is not available (possible private browsing mode). Session persistence disabled.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: authConfig
});